---
envs:
  testnet:
    packages:
      ika_package_id: "0x1f26bb2f711ff82dcda4d02c77d5123089cb7f8418751474b9fb744ce031526a"
      ika_common_package_id: "0x96fc75633b6665cf84690587d1879858ff76f88c10c945e299f90bf4e0985eb0"
      ika_dwallet_2pc_mpc_package_id: "0xf02f5960c94fce1899a3795b5d11fd076bc70a8d0e20a2b19923d990ed490730"
      ika_system_package_id: "0xae71e386fd4cff3a080001c4b74a9e485cd6a209fa98fb272ab922be68869148"
    objects:
      ika_system_object_id: "0x2172c6483ccd24930834e30102e33548b201d0607fb1fdc336ba3267d910dec6"
      ika_dwallet_coordinator_object_id: "0x4d157b7415a298c56ec2cb1dcab449525fa74aec17ddba376a83a7600f2062fc"
  local:
    packages:
      ika_package_id: "0x72df31107050fa403a6a9d50199d5e40d77f2ea95e1dbe172ead404957007550"
      ika_common_package_id: "0x1d19ebafc8d7509f529adee2029dfca48462a4ad90dbbba3b7b6aa178e7dd86b"
      ika_dwallet_2pc_mpc_package_id: "0x04ad8d66a99cee7d723312deb127f4de378243e3306295727593ad5523b7d84b"
      ika_system_package_id: "0xb5a37c87ac2f57c3d4db8afa963d04be7862331616b01e8986e534123d506e95"
    objects:
      ika_system_object_id: "0x06430cd1a1c80929db81f4755e837767b7bc3572a706c25bbc050e8e137be387"
      ika_dwallet_coordinator_object_id: "0x417a7e79279c60c97a2903690b28db4f98f3e9b605005965d3d80d71bca3aae5"
  mainnet:
    packages:
      ika_package_id: "0x7262fb2f7a3a14c888c438a3cd9b912469a58cf60f367352c46584262e8299aa"
      ika_common_package_id: "0x9e1e9f8e4e51ee2421a8e7c0c6ab3ef27c337025d15333461b72b1b813c44175"
      ika_dwallet_2pc_mpc_package_id: "0xdd24c62739923fbf582f49ef190b4a007f981ca6eb209ca94f3a8eaf7c611317"
      ika_system_package_id: "0xb874c9b51b63e05425b74a22891c35b8da447900e577667b52e85a16d4d85486"
    objects:
      ika_system_object_id: "0x215de95d27454d102d6f82ff9c54d8071eb34d5706be85b5c73cbd8173013c80"
      ika_dwallet_coordinator_object_id: "0x5ea59bce034008a006425df777da925633ef384ce25761657ea89e2a08ec75f3"