name: TypeScript Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'sdk/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
  PROFILE: dev

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH for manual git
        if: env.GH_DEPLOY_KEY
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        if: env.GH_DEPLOY_KEY
        run: |
          git config --global url."git@github.com:dwallet-labs/cryptography-private".insteadOf "https://github.com/dwallet-labs/cryptography-private"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          # Version of pnpm to install, must match `package.json` "packageManager" field.
          version: 9.1.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'pnpm'

      - name: Install wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Install Sui from Github
        run: |
          curl -L https://github.com/MystenLabs/sui/releases/download/mainnet-v1.58.3/sui-mainnet-v1.58.3-ubuntu-x86_64.tgz > sui.tgz
          tar -xvzf sui.tgz
          sudo cp ./sui /usr/local/bin/sui

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sdk/typescript

      - name: Format Check
        run: pnpm run prettier:check
        working-directory: ./sdk/typescript

      - name: Build
        run: pnpm run build
        working-directory: ./sdk/typescript

      - name: Lint
        run: pnpm run eslint:check
        working-directory: ./sdk/typescript
